theme: jekyll-theme-primer
title: Lending Club
description: Create loan-level default prediction models 
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
